/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kingpei_lameproject_Mp3Encoder */

#ifndef _Included_com_kingpei_lameproject_Mp3Encoder
#define _Included_com_kingpei_lameproject_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kingpei_lameproject_Mp3Encoder
 * Method:    init
 * Signature: (Ljava/lang/String;IIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_kingpei_lameproject_Mp3Encoder_init
  (JNIEnv *, jclass, jstring, jint, jint, jint, jstring);

/*
 * Class:     com_kingpei_lameproject_Mp3Encoder
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kingpei_lameproject_Mp3Encoder_encode
  (JNIEnv *, jclass);

/*
 * Class:     com_kingpei_lameproject_Mp3Encoder
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kingpei_lameproject_Mp3Encoder_destroy
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
